# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
sudo: required # https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
dist: xenial
python:
  - 3.7
  - 3.6
  - 3.5

install: pip install -U tox-travis

script: tox

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rooter
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: rooterkyberian/elen
    python: 2.7
